import SwiftUI
import AppKit
import Riptide
import Sparkle

// Shared coordinator — holds the main window reference for the entire app
@MainActor
final class AppCoordinator {
    static let shared = AppCoordinator()
    var mainWindow: NSWindow?

    // Sparkle 2.6+ configuration:
    //   - Feed URL (SUFeedURL) and public edDSA key (SUPublicEDKey) are read
    //     from Riptide.entitlements at runtime by Sparkle.framework. We do
    //     NOT set them programmatically here — that's the recommended path.
    //   - The private signing key lives outside the repo at
    //     ~/Keys/riptide-sparkle-ed25519.pem (generated by
    //     Scripts/sign-sparkle-update.sh keygen) and in the
    //     SPARKLE_PRIVATE_KEY GitHub Secret for CI use.
    //   - See Resources/sparkle-pubkey.pem for the public key record.
    lazy var updaterController: SPUStandardUpdaterController = {
        SPUStandardUpdaterController(
            startingUpdater: true,
            updaterDelegate: nil,
            userDriverDelegate: nil
        )
    }()

    private init() {}
}

@main
struct RiptideApp: App {
    @State private var appVM = AppViewModel()
    @State private var statusBar: StatusBarController?
    @StateObject private var themeManager = ThemeManager()
    @StateObject private var hotkeyManager = HotkeyManager()
    @AppStorage("hasCompletedOnboarding") private var hasCompletedOnboarding = false

    private var shouldShowMainUI: Bool {
        if ProcessInfo.processInfo.environment["RIPTIDE_UI_TEST"] == "1" {
            return true
        }
        return hasCompletedOnboarding
    }

    var body: some SwiftUI.Scene {
        WindowGroup {
            Group {
                if shouldShowMainUI {
                    MainTabView(vm: appVM, themeManager: themeManager)
                        .accessibilityIdentifier(A11yID.App.mainWindow)
                        .preferredColorScheme(colorScheme)
                        .frame(minWidth: 800, minHeight: 500)
                } else {
                    OnboardingView(isPresented: Binding(
                        get: { !hasCompletedOnboarding },
                        set: { newValue in hasCompletedOnboarding = !newValue }
                    ))
                }
            }
            .onOpenURL { url in
                // LaunchServices delivers `riptide://...` URLs here when
                // the user runs `open riptide://mode?value=off` and the
                // .app bundle's Info.plist declares the scheme (see
                // Scripts/build-release.sh). Wrapping both branches in a
                // Group ensures the handler fires regardless of whether
                // onboarding is showing or the main UI is up.
                Task { @MainActor in
                    _ = await URLSchemeHandler.route(url, viewModel: appVM)
                }
            }
            .onAppear {
                guard self.statusBar == nil else { return }

                // Request notification permission on first launch — only prompts
                // when the user has not yet made a decision in System Settings.
                let notifManager = UserNotificationManager.shared
                Task { @MainActor in
                    await notifManager.requestAuthorizationIfNeeded()
                }

                // Center window on screen
                if let window = NSApp.windows.first,
                   let screen = NSScreen.main ?? NSScreen.screens.first {
                    let screenFrame = screen.visibleFrame
                    let windowSize = window.frame.size
                    let centerX = screenFrame.origin.x + (screenFrame.width - windowSize.width) / 2
                    let centerY = screenFrame.origin.y + (screenFrame.height - windowSize.height) / 2
                    window.setFrameOrigin(NSPoint(x: centerX, y: centerY))
                    window.setAccessibilityIdentifier(A11yID.App.mainWindow)
                    AppCoordinator.shared.mainWindow = window
                    appVM.mainWindow = window
                }

                // Create the single status bar item (AppKit)
                let bar = StatusBarController()
                bar.setup(vm: appVM)
                self.statusBar = bar

                // Install the Touch Bar (only visible on Touch Bar hardware —
                // 2016-2021 MacBook Pros). No-op elsewhere.
                TouchBarProvider.shared.appViewModel = appVM
                AppCoordinator.shared.mainWindow?.touchBar = TouchBarProvider.shared.makeTouchBar()

                // Register global keyboard shortcuts. The handler hops to
                // MainActor so it can safely mutate AppViewModel state from
                // the NSEvent monitor callback thread.
                hotkeyManager.registerHotkeys { action in
                    Task { @MainActor in
                        await appVM.handleHotkeyAction(action)
                    }
                }
            }
        }
        .defaultSize(width: 900, height: 600)
        .commands {
            CommandGroup(after: .appInfo) {
                Button("检查更新…") {
                    AppCoordinator.shared.updaterController.checkForUpdates(nil)
                }
                .keyboardShortcut("u", modifiers: [.command, .shift])
            }
        }
    }

    private var colorScheme: ColorScheme? {
        switch themeManager.appearanceMode {
        case .system: return nil
        case .light:  return .light
        case .dark:   return .dark
        }
    }
}
